### ISSUE TITLE
Structural changes

### ISSUE THREAD

**Issue by suntong** [go-easygen/easygen#10]
Structural changes so as to make enabling #9 feasible and easy.

**Comment by suntong** [comment]
Reiterate from #9, here is the goal:

- For adding the consul template functions, 
  * I had done some thinking along this path, and had once thought to refactor the `github.com/danverbraganza/varcaser/varcaser` dependency out to a sub module. I.e., for people to use it, they need to import `github.com/go-easygen/easygen` ***and*** `github.com/go-easygen/easygen/ext` or something like that. 
  * The ultimate goal is to make it simple for `easygen` to be a building block that people can easily extend, but I haven't figured out a good way of doing that yet. 
  * As for `minus1`, I had once thought to change it to just a generic `add` , which takes an extra parameter of `-1`, so _add -1_ becomes `minus1`. However, due to the limitation of go template, which accepts only one parameter, I was stopped. Maybe I didn't look far enough. So do you think that if we do something like [consul template functions](https://github.com/hashicorp/consul-template/blob/de2ebf4/template_functions.go#L727-L901), we can use those generic template functions?

**Comment by suntong** [comment]
It'll be a complete overhaul, so please stick to http://gopkg.in/easygen.v1 for now until it gets stable.

**Comment by grrtrr** [comment]
This sounds great. Are you thinking in terms of modules or plugins? 

Go now has the ability to load shared libraries, maybe that would be an idea.

For me, I would probably go ahead and grab every possible extension. It would not change the size of the binary and provide all features without extra configuration effort. Just simple.

**Comment by suntong** [comment]
Take a look at this:
https://github.com/go-easygen/easygen/blob/restructure/example_test.go#L47-L49

This is where I want to go -- the end user picks and choose what he wants from the library. Of course, the `easygen` itself will load everything.

**Comment by grrtrr** [comment]
:+1: Good  -- API is modular and it is clear from the code and conventions how each module represents itself. Could imaging things like `egStrings`, `egDate` etc to come. This is looking good!

**Comment by suntong** [comment]
fixed in v2.1.0
