### ISSUE TITLE
Changing the fundamental data type

### ISSUE THREAD

**Issue by suntong** [go-easygen/easygen#17]
Currently, the fundamental EasyGen driven data type is defined as: 

```go
// EgData -- EasyGen driven Data
type EgData map[interface{}]interface{}
```

I'm thinking to change it to `map[string]interface{}` instead, as it is not possible to Converting [type map[string]interface {}](https://github.com/fatih/structs#usage-and-examples) to type map[interface {}]interface {}

https://play.golang.org/p/VU4ND_6JU_
https://golang.org/doc/faq#convert_slice_of_interface
https://groups.google.com/d/msg/golang-nuts/3pgc2cB-GFY/5Y4fikHPCAAJ

This should not cause any problem in theory, @grrtrr, would you see if any? Thx.

**Comment by grrtrr** [comment]
Good move. The [more concrete](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=7m36s) you can make the type, the better. It then is also easier to see what the map does, i.e. what kind of key.

**Comment by suntong** [comment]
Thanks for the input, will do...

**Comment by suntong** [comment]
Revisiting this topic as I've found that my existing code is broken, when [converting from V1 to V2](https://github.com/go-easygen/easygen/issues/20). 

V1 allows arbitrary data like this, 

```go
type Inventory struct {
	Material string
	Count    uint
}
```

and so does the text Template. However, V2's `map[string]interface{}` type is to restrictive. 

Will reopen it so as to make it accepting any arbitrary data, just like the text Template does. 

Ref:
https://play.golang.org/p/MKY9Bq-H-AL
