### ISSUE TITLE
command-line replacing options re-engineering 

### ISSUE THREAD

**Issue by suntong** [go-easygen/easygen#19]
> With regard to the command-line options for replacing strings (from -> to), would it be possible to express them in terms of a string template function (i.e. solve the conflict he other direction)?

Separating into a new thread to discuss further, @grrtrr. 

So Gerrit, that indeed seems to be a good idea. What have you in mind? Thx.

**Comment by grrtrr** [comment]
Thank you for following up. I need to study the source code. Will get back before Saturday noon if that is ok.

**Comment by suntong** [comment]
NP at all. We do need time to think it through carefully. Take yours.

**Comment by suntong** [comment]
I actually agree. It is now unnecessary, with the fix to #18. 

Let me warn people first, that such disruptive change will be happening soon...

**Comment by suntong** [comment]
changes pushed to 

https://gopkg.in/easygen.v3 
i.e., https://github.com/go-easygen/easygen/tree/v3.0.0
