### ISSUE TITLE
New disruptive API change for V3: Using ENV

### ISSUE THREAD

**Issue by suntong** [go-easygen/easygen#21]
Don't know how many of you are using the `.ENV` to access environment variables (e.g., `{{.ENV.SHELL}}`), but because of the difficulties fixing #17, to make `easygen` accepting any arbitrary data again, the cleanest solution is to turn `.ENV` into a function. 

So in V3, instead accessing environment variables like e.g., `{{.ENV.SHELL}}` use `{{ENV "SHELL"}}` instead.

**Comment by suntong** [comment]
@grrtrr, please take a look at this and tell me if it'll break your code. 

FYI, I've checked in the change into a branch,  https://github.com/go-easygen/easygen/commits/v3
together with the CLI change you raised.

**Comment by grrtrr** [comment]
No, that is fine, thank you for keeping on improving this tool.

**Comment by suntong** [comment]
Thanks Gerrit, I'll merge it in then.
