### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by suntong** [go-easygen/easygen#37]
Add contributors

**Comment by suntong** [comment]
@all-contributors please add @grrtrr for code, ideas, bug, userTesting

**Comment by suntong** [comment]
@all-contributors please add @grrtrr for talk, content, blog, and add @bruston for code, bug, userTesting

**Comment by suntong** [comment]
@all-contributors please add @grrtrr for talk, content, blog
@all-contributors please add @bruston for code, bug, userTesting

**Comment by suntong** [comment]
@all-contributors please add @grrtrr for talk, content, blog

**Comment by suntong** [comment]
@all-contributors please add @bruston for code, bug, userTesting

**Comment by suntong** [comment]
@all-contributors please add @sanjaymsh for platform

**Comment by suntong** [comment]
@all-contributors please add @anthonyfok  for bug, review,  maintenance, userTesting

**Comment by suntong** [comment]
@all-contributors please add @ghost for bug, ideas, userTesting

**Comment by suntong** [comment]
@all-contributors please add @romz-pl for bug, ideas, userTesting

**Comment by suntong** [comment]
thx

**Comment by grrtrr** [comment]
> @suntong
> 
> I've put up [a pull request](https://github.com/go-easygen/easygen/pull/39) to add @grrtrr! tada

Hi Suntong, thank you for remembering me. I did not do that much. `easygen` has been such a great help to us, making so many mundane tasks easier (and fun) to do.

**Comment by suntong** [comment]
Oh, it's so nice to hear from you again @grrtrr. 
Thanks for those nice words, they are truly music to my ears. 

Also glad to know that you're still using easygen. Recently I had a fun experience as well. So I

- download `json` data via API
- filter the `json` data with my [`jp`](https://github.com/go-jsonfile/jp/releases/tag/v0.2.2) that supports filtering by regular expression
- then present the `.json` data in human friendly format with my new `easygen` that can read from `stdin` now.
- in the human friendly form, I need to convert the long number of size in bytes to the size in MB and GB, and I had to search for how to do calculation in Go template, and was _delighted_ to realized that I've _already_ put the [calculation in Go template](https://github.com/go-easygen/easygen/issues/25#cal) in `easygen` long ago 😄😄😄.  To me now,

`easygen` is to `json` what `xslt` is to `xml`, but much stronger

Ah, BTW, is it OK that I quot your nice words at the top of easygen's README as a testimony? thx!

**Comment by grrtrr** [comment]
> Ah, BTW, is it OK that I quot your nice words at the top of easygen's README as a testimony? thx!

Sorry no, that was just a message.

**Comment by suntong** [comment]
> `easygen` has been such a great help to us, making so many mundane tasks easier (and fun) to do.

This line only, and I'll skip providing who said that. 

OK?
